### ISSUE TITLE
Google SearchBar not removable

### ISSUE THREAD

**Issue by Bmme2GFTbU** [copperhead/bugtracker#121]
The GoogleSearchBar got no function and can only be removed with another launcher. Maybe the SearchBar should be finally removed.

**Comment by thestinger** [comment]
It can technically be removed by disabling the Search app.

The area of the launcher it uses would simply be dead space without it since it's where the actions are displayed when dragging something. It's unmaintained so it still uses an ancient theme but it's not completely useless and it needs to be replaced with a modern implementation rather than removed.

It's not a unique case: most of the built-in apps are awful and need to be replaced. So far, the obsolete AOSP Browser app has been replaced with a build of Chromium.

**Comment by thestinger** [comment]
Closing in favor of #123. Suggestions for alternatives to the obsolete AOSP apps are welcome. The replacements need to be open-source and well-maintained.
