### ISSUE TITLE
support toggling the INTERNET permission off and on

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#128]
It's currently implemented via a group id, so dynamically toggling it might not be trivial. It could be implemented by providing a secondary dynamic layer with iptables rules if necessary. There's already code in the netd service doing something similar for features like Doze.

**Comment by eighthave** [comment]
The problem with the network permission is that there are ways around it.  I think this still applies in Android: https://threatpost.com/android-application-allows-remote-access-no-permissions-required-122011/76017/

I think that's why Google is granting the network permission automatically these days.

**Comment by thestinger** [comment]
@eighthave There aren't any details there. Google doesn't grant it automatically. They only stopped marking it as a dangerous permission. They did that because then it wouldn't be enabled by default for the new API levels rather than simply being listed on installation. Every app would need to learn to check for it and request it from the user. It would be too painful for users and developers.

**Comment by thestinger** [comment]
This is now implemented.
