### ISSUE TITLE
provide an API for performing full transparent proxying on a per-app and full system basis without leaks

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#130]

**Comment by thestinger** [comment]
Orbot has experimental support for Android's VPN API, so this is less urgent. It can proxy all app traffic without root, although there may be leaks or other flaws.

**Comment by vladimir-lu** [comment]
Do you have any thoughts on the design already? I'm interested in helping to implement this.

Btw the fact that Orbot supports the VPN API is a nice workaround currently, but then you're not able to use a VPN-based firewall (like NetGuard) because of the single VPN provider limitation (though perhaps you could multiplex those two specifically - probably very hacky though). So I imagine this is going to have to be iptables-based?
