### ISSUE TITLE
Updating via OTA breaks TWRP on Nexus 5

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/bugtracker#155]
Hi
By now I did two OTA updates and both times I couldn't boot back into recovery to flash superuser right after the updates. The phone only shows the droid with the triangle on top. It seems like the OTA update damages twrp iin some way.

I had to flash twrp manually. When I flash updates via adb sideload, twrp stays untouched. Is this an issue of TWRP or of CopperheadOS?

**Comment by thestinger** [comment]
CopperheadOS updates the recovery image when it performs an OTA update, so it has switched you back to the stock recovery. In user builds, you need to hold the power button and press volume up to get to the menu because it doesn't want to drop users into a dangerous menu if there's an error. Keeping the recovery up-to-date is important and the intention is that people use the official recovery image so that there's proper signature verification, so it's not going to be worked around.

**Comment by polyzen** [comment]
Bundling the recovery started in 2016-01-28?

**Comment by thestinger** [comment]
It started when CopperheadOS moved to AOSP but the `applypatch` tool had memory corruption detected by OpenBSD malloc so it wasn't working.

**Comment by thestinger** [comment]
See https://github.com/CopperheadOS/platform_bootable_recovery/commits/marshmallow.

**Comment by thestinger** [comment]
It also might not have happened before the switch to proper OTA updates via Android's `RecoverySystem.installPackage` API.

**Comment by polyzen** [comment]
Well, I'm on 0120, and have a couple ways to keep TWRP(, Superuser, and GApps).

If you use the updater, you will have to babysit the update. Boot back into TWRP just after the update finishes, before Android boots. If you do not, a recovery (not sure if Android or ChOS) will get installed during that boot. This gives you a change to update/re-flash Superuser/GApps, if that's your thing.

or

Get the latest installers for your stuff -> boot into TWRP -> install/sideload

**Comment by vanitasvitae** [comment]
I think I'll then go for manual download&sideload of new images and avoid using OTA.
