### ISSUE TITLE
feature request: hold back to kill

### ISSUE THREAD

**Issue by neo-luddite** [copperhead/bugtracker#157]
hold back to kill:
many custom roms got this feature which kills any app by long-pressing the back button.

quick unlock:
the PIN and Password unlock screens are unlocked as soon as the correct pin/password is entered, without having to press the enter key to submit.

I'm using coppherheados on nexus 5 now for a few days as daily, till now everything is smooth. thanks for development!

**Comment by thestinger** [comment]
> many custom roms got this feature which kills any app by long-pressing the back button.

Can you explain the use case for it? I might be interested in adding it but it hasn't been something I've personally wanted to have.

> the PIN and Password unlock screens are unlocked as soon as the correct pin/password is entered, without having to press the enter key to submit.

That's it's incompatible with the gatekeeper throttling so it's not going to be implemented. It's why it was removed from CyanogenMod 13.0. It's bad for security too, since it provides a minor convenience at the expense of making it significantly easier to break in.

> I'm using coppherheados on nexus 5 now for a few days as daily, till now everything is smooth. thanks for development!

Glad it's working well for you.

**Comment by neo-luddite** [comment]
> pin and password
well, I gave it some more thoughs and totally agree with you. Guess I just was missing it because I got used to it.

> Can you explain the use case for it? I might be interested in adding it but it hasn't been something > I've personally wanted to have.
when using my laptop I close programms I don't use anymore. Just sending everything in the background on android is something I don't feel comfortable with. Especially with the  proprietary programms I have to use (e.g. photo tan for banking, local tranport schedule...). I can be kinda sure that the app isn't doing anything in the background anymore. It's much mor convenient with this feature than opening preferences, app dialog, selecting the app and forcing it to close. 
also if an app hangs it's just one long button press and its gone.

one more suggestion: maybe add some more info in the documentation about the security settings options (full data sanitation...), which ones are kinda 'save' to enable and if things are not working anymore in which order to disable them.

btw: netguard as non-root firewall works pretty good. maybe also mention this in the documentation because I guess many security aware users are really missing the capability to manage iptables on a non rooted phone and restricting apps accessing the internet.

**Comment by thestinger** [comment]
I don't plan on implementing any non-security / non-privacy-related features. The development and maintenance burden will detract from security features. It's out of scope for CopperheadOS. If you want features like this, you should get AOSP to implement them and then they'll be available in CopperheadOS too.

**Comment by cwmke** [comment]
@thestinger While I appreciate your thoughts and decision to not implement non-security features, I would ask you to reconsider adding some smaller niceties that AOSP will never implement.  AOSP is geared towards a broad category of applications and therefore will ignore many of the missing features that can greatly improve the useablity of a phone.

Baking small features such as long pressing the recents button to immediately switch to the previous app or swiping down from the right side of the notification bar to immediately pull down the quick settings panel will improve the function of the rom and I imagine, also bring more users.  I personally am coming here from Omni Rom which I felt had a great set of built-in customization options.

Many of these features are widely implimented across other roms and are included in open source roms such as @omnirom.  Since su (understandably) will not be implemented, modifying our rom to our individual preferences becomes extremely difficult if not impossible.  Most customization options come from either the rom, Xposed or something manipulated utilizing root access.

My appologies for the length of this comment.  I understand you have limited time and would prefer to focus solely on security issues but I hope that small efforts can be made in the future to implement a few non-security ideas in the future.  Thanks for all of your time and efforts spent on this incredible OS!

**Comment by thestinger** [comment]
It's not going to be reconsidered. If you want non-security-related features to be included in CopperheadOS, then work towards getting them included in Android. CopperheadOS is not intended to be anything other than stock Android with many added hardening features and without Google Play. The only non-security-related enhancements that are in-scope for the project are those replacing functionality lost by not having Google Play and those are going to be very low-priority issues. That's why including F-Droid and a build of Chromium are in-scope for the project. Android N already added returning to the most recently used app via double-tapping the recent apps button so no point in worrying about that as it will be available.

**Comment by cwmke** [comment]
Fair enough. Thanks for taking the time to respond.
