### ISSUE TITLE
Install Playstore

### ISSUE THREAD

**Issue by Heimdal300** [copperhead/bugtracker#161]
Hello,

I know its not good, but I want to install the Google-Playstore in Copperhead OS (for Signal and some other apps). Is there any way? On Twitter I read that it there is a way to flash twrp-recovery over the Copperhead Recovery to make unsigned sideloading possible, but this didn't worked for me. I use a Nexus 5 and have the latest Copperhead update (02.02). The old Tutorial from the Copperhead-Blog (https://copperhead.co/blog/2015/08/21/alpha) doesn't work anymore.
Can anyone help? I would be really nice to change back to the Copperhead-recovery after the gapps install. Is there perhaps a way to get a signed gapps-package or disable the signature-check manually for a short time?

Thank you very much!

**Comment by thestinger** [comment]
It's not really supported anymore. It will be wiped away on every update due to block-based rather than file-based updates and it's incompatible with verified boot / locking the bootloader (although dm-verity isn't used on the Nexus 5). There's no guarantee that it will continue being possible to use it but it still works fine for now.

You need to use a gapps package designed for Android 6.0. You can sideload it with TWRP and switch back to Copperhead's recovery. Since 6.0, gapps will also hit lots of permission errors (with other ROMs like CyanogenMod too) unless it's installed before the first boot with a clean userdata partition so you'll need to work around those by toggling on the permissions.

**Comment by burdges** [comment]
There is a more recent method for doing this in https://github.com/mikeperry-tor/mission-improbable/ but it's rather involved and includes creating your own keys for verified boot, probably a serious bricking risk.  I'd suggest that people really interested in this consider trying to broaden that project to other devices, or at the extreme fix the security issues with microG.  

In all honesty, the easiest approach might be to file bug reports with a few select apps that use push notifications, like WhatsApp and maybe Wire.  If those switched to signal's more aggressive approach, then installing these apps would drain battery faster, but notifications would not be delayed until the user activates the application.

**Comment by thestinger** [comment]
WhatsApp and Wire already do push without GCM. They might not be adapted to Doze / App Standby yet but otherwise they work.

**Comment by burdges** [comment]
Yes, that's all I meant.
