### ISSUE TITLE
Feature Request: A Knox like Spaces Feature

### ISSUE THREAD

**Issue by PandorasTeacup** [copperhead/bugtracker#164]
Samsung has a Software called Knox, which also Blackberry uses. Graphite Software developed something similar and released a ROM called Secure Spaces and the Blackphone 2 uses their Software.

This Software allows you to create seperate Spaces to keep your sensitive Data away from your Games for example, or to Hide your sensitive Data in a Hidden Space.

I couldnt find any Open Source Solution for Android, only these two proprietary Solutions. But i found a Open Source Sailfish OS App which starts Android in a Sandbox, which is basically what Knox and Secure Spaces do, I think.

Samsung Knox:
https://www.samsungknox.com/en

Graphite Softwares Secure Spaces ROM:
http://www.securespaces.com/WP2015/

Silent OS's Spaces:
https://www.silentcircle.com/products-and-solutions/devices/silent-os/#section_3

Android Renderer by krnlyng:
https://github.com/krnlyng/android_renderer

**Comment by thestinger** [comment]
Android has a proper built-in multi-user feature since Lollipop that's usable for isolated workspaces. It even has an ephemeral guest account. It doesn't currently have features like per-user directory encryption but it could. It's unlikely that it will be implemented in CopperheadOS because it already seems to be on Google's roadmap, perhaps for 7.0. Hidden accounts would be possible but that's a separate feature request from the baseline feature that's already present.

**Comment by thestinger** [comment]
Since 6.0, Android also uses SELinux MLS for the multi-user implementation so it's a lot more secure than 'Secure' Spaces.

**Comment by PandorasTeacup** [comment]
Sorry, didn't know that. The last Android Version I used was 2.3 and I should have checked if this was implemented since then.
