### ISSUE TITLE
Chatsecure and Xabber not working through Orbot/Tor on Nexus 5

### ISSUE THREAD

**Issue by lagosazules** [copperhead/bugtracker#177]
Nexus 5 Chatsegure and Xabber are not working or crashing when activating Orbot using latest versions from F-Droid.
- Chatsegure not connecting or crashing when activating a new or burn account through Orbot.  
- Xabber correct configurated through Orbot is not using Tor, because exiting de Orbot app don't stop the Xabber connection.

Not rooted offcours and normaly no root is needed for this apps on Orbot

**Comment by thestinger** [comment]
I need the relevant logs from `adb logcat` to approach an issue like this.

**Comment by lagosazules** [comment]
Sorry  for this post, but this is not a bug in Copperhead but a bug in Chatsegure on Android 6.0
https://dev.guardianproject.info/issues/6576

**Comment by nexus4fun** [comment]
Hello, seems that Orbot + Chatsecure isn't working only on Cooperhead OS. The ChatSecure bug for Android 6.0 was fixed in version 14.2.3. I have AOSP Rom on my Moto G (Android 6.0.1) and Orbot + ChatSecure is working without any issues. On Cooperhead OS, seems that ChatSecure can't find Orbot, as it always show "Orbot doesn't appear to be runing.." I really like the work you are doing, but is there any possibility to fix this issue? If you need any more information about this issue, pleas say me what i must do :) as i am begginer...

**Comment by thestinger** [comment]
Can you open a new bug about that? It's a different issue. It might be caused by `hidepid=2`.
