### ISSUE TITLE
SMSsecure can't be updated with F-Droid

### ISSUE THREAD

**Issue by ciaby** [copperhead/bugtracker#181]
Just flashed the latest image for the Nexus 5 (MMB29U.2016.02.07.14.31.34). If I try to update SMSsecure within F-Droid, it can't do it because it's signed by a different key. Obviously I can't uninstall it because it's in the base image :)

**Comment by thestinger** [comment]
It's supposed to be that way. It's our own build rather than bundling a third party build as part of the OS. It's updated in the source tree and will be pushed out with the next build. I wanted to do a build already but I decided to wait until someone posts logs in https://github.com/copperhead/bugtracker/issues/170 so I can roll that fix into the next build. It's starting to look like that's not going to happen so I'll just do the builds without it.

**Comment by ciaby** [comment]
I see, thanks for clarifying it :) Make sense actually, at least it's a trusted build.
