### ISSUE TITLE
Double free detection is causing some errors with Chrome

### ISSUE THREAD

**Issue by Fuzion24** [copperhead/bugtracker#187]
https://gist.github.com/Fuzion24/1bac9d9eff0402d3796a

**Comment by thestinger** [comment]
Does it crash consistently or is this just an intermittent issue?

**Comment by thestinger** [comment]
The error happens when an allocation is freed but there's no entry for the page in the region hash table. So it's a pointer to memory that's not currently handed out as a malloc allocation. It's one of the baseline OpenBSD malloc features rather than a CopperheadOS extension.

**Comment by thestinger** [comment]
So this might be a double-free, but it could also be `free(invalid_ptr)` where `invalid_ptr` was allocated with another allocator or something like that. It would be very helpful if you could provide tombstones. It would show whether the memory at that address is actually mapped and it might be labelled. Could add a debugging feature to OpenBSD malloc to label all the memory properly too - just didn't do that because it hits `mmap` quite a bit and adding the `prctl` call would add significant overhead.

**Comment by thestinger** [comment]
This needs to be reconfirmed with a new Chrome version and I don't think there's any way it's a CopperheadOS bug.
