### ISSUE TITLE
Unable to add google account

### ISSUE THREAD

**Issue by olibd** [copperhead/bugtracker#199]
I am unable to add my google account under settings -> Accounts. The app just freezes.

Nexus 5 - Copperhead Os version 	MMB29V.2016.03.07.22.19.43

**Comment by thestinger** [comment]
Going to need logs from `adb logcat`. I assume you have gapps sideloaded? Since that doesn't seem to show up as an option without it. I suspect that it's just a regular gapps issue rather than a CopperheadOS issue but need logs to determine that.

**Comment by polyzen** [comment]
And could you be more specific about when it crashes?

**Comment by olibd** [comment]
@thestinger Yes it was due to gapps, and unfortunately I won't be able to provide a log because they made OS unusable so I had to re-install. These gapps were not sideload, most of them can be installed directly from an their APK (Sideloaded Gapps (from OpenGapps) don't seem to be compatible with copperhead). I installed Google Play Services and Google Play Store, Google Play Services seemed to work but the Play Store kept crashing. I thought that signing into my google account from the preferences would help, but as mentionnned in the original post, the settings' app just froze. I wish I could provide more details, let me know if you guys have any question. Copperhead is really cool and better support of Gapps would make it a top notch custom ROM so anything I can do to help, let me know.

**Comment by olibd** [comment]
@polyzen the app freezes when confirming the credentials

**Comment by thestinger** [comment]
OpenGapps is no less compatible with CopperheadOS than it is with other AOSP-based ROMs like CyanogenMod without hard-wired hacks to work around the issues with it. At least, I'm not aware of any compatibility issues with CopperheadOS that would not happen with AOSP and I don't think this is one. It's not officially supported so it's up to you to cope with the pain of using it: you need to manually toggle on a bunch of dynamic permissions and you can't use over-the-air updates. You need to sideload each update and then sideload gapps again.

It can *never* be supported well. It *must* be bundled for it to be compatible with verified boot and updates. It also has to be built-in to the OS to avoid these permission issues. None of that can happen due to the licensing.

**Comment by thestinger** [comment]
Installing the individual apps won't work since they depend on Play Services.

**Comment by olibd** [comment]
@thestinger thank you for the clarification :)
