### ISSUE TITLE
Recurrent QSEECOMD error in logcat (logged every 10 seconds)

### ISSUE THREAD

**Issue by xmikos** [copperhead/bugtracker#224]
I see recurrent QSEECOMD error in logcat, logged every 10 seconds:

```
04-01 10:34:01.142 D/QSEECOMD: (18715): qseecom listener services process entry PPID = 1
04-01 10:34:01.142 E/QSEECOMD: (18715): Listener: index = 0, hierarchy = 0
04-01 10:34:01.142 E/QSEECOMD: (18715): Init dlopen(librpmb.so, RLTD_NOW) is failed....
04-01 10:34:01.142 E/QSEECOMD: (18715): ERROR: RPMB_INIT failed, shall not start listener services
```

This is on Nexus 5. And I suspect this causes worse battery life (but I am not sure about that).

**Comment by thestinger** [comment]
That's because of #88. The Nexus 5 builds use the official driver bundles from Google, and there are some missing components. It means WideVine DRM won't work but doesn't really have other implications. It might impact battery life.

Since this only impacts older devices, I'm unlikely to do anything about it myself. My focus is going to be on current generation devices. Someone needs to figure out the list of missing binary blobs that are not part of Play Services and friends. The process of grabbing them from the factory images needs to be automated if they're going to be included.

For the 5X, 6P and 9, there's https://github.com/anestisb/android-prepare-vendor.

**Comment by xmikos** [comment]
@thestinger I can look into it, I would really like if Nexus 5 is fully supported.

Btw. are you sure about WideVine DRM not working completely? I have tried Google Play Movies and Netflix (both uses WideVine DRM if I am not mistaken). And Netflix works, only Google Play Movies doesn't.

**Comment by xmikos** [comment]
Also doesn't this affect hardware encryption (TEE) too?

**Comment by thestinger** [comment]
Not sure. That would be a problem if it did.
