### ISSUE TITLE
Bootloop after factory reset

### ISSUE THREAD

**Issue by mhyqwvcu** [copperhead/bugtracker#248]
Did an OTA update for Nexus 5x bullhead-ota_update-2016.04.26.16.55.03.zip

Update completed successfully, did a reboot. Proceeded to do a factory reset. Device rebooted a few times, showed Android lying on its back with a red !triangle "No Command". Subsequent reboots replicate previous activity.

**Comment by thestinger** [comment]
The red triangle is recovery. Maybe it's not working because it was removed from the menu.

**Comment by mhyqwvcu** [comment]
Somehow it worked after rebooting a few more times, gave me a scare though. Should I close this?

**Comment by thestinger** [comment]
If it happens again you can bypass the recovery screen by holding power + volume up and then you can manually reboot. Not sure why this would happen. It's probably an upstream bug, but it's possible that it only occurs on CopperheadOS due to a feature that's uncovering it. I suspect something like a use-after-free that's *sometimes* uncovered by OpenBSD malloc.

**Comment by mhyqwvcu** [comment]
Thanks for your support. I sincerely appreciate it and wish this project the best.

**Comment by thestinger** [comment]
I can sometimes reproduce problems rebooting to the recovery (which is how factory resets work) on the 5X and 9, so I'll keep trying to figure that out. I expect it's the same as whatever you ran into. It needs a userdebug build so there's not much you can do (and even then it's probably tricky).
