### ISSUE TITLE
alarm not working properly in nexus 6p

### ISSUE THREAD

**Issue by subproc** [copperhead/bugtracker#272]
hi, if i set an alarm it will work if the screen it's not sleeping. If it is, or it's locked, when it's the hour the alarm play just a second and then stop...on the screen you can see snooze or dismiss, but no sound

**Comment by thestinger** [comment]
This is an upstream AOSP issue on the 5X and 6P. I recommend using a different clock application for now. Fixing this in CopperheadOS isn't planned since these DeskClock issues aren't caused by any of our changes and the app is completely screwed up in this branch. We would accept patches fixing the issues, if someone is interested in working on fixing it.
is completely screwed up in this branch. We would accept patches fixing the issues if someone else is interested in working on it, but it's really an AOSP bug.

This was previously filed as #231.

**Comment by thestinger** [comment]
Also, which locale do you use? I assume it's not US English?

**Comment by subproc** [comment]
it's not my language but i use US English

**Comment by subproc** [comment]
and i have the same problem of alxxlc in #231, but i use another app waiting for a fully operative desclock... ;-)

**Comment by thestinger** [comment]
There's unlikely to be progress here. It's an AOSP issue and Google isn't going to be interested in fixing it. We don't have the resources to deal with AOSP bugs like this.
