### ISSUE TITLE
default apps

### ISSUE THREAD

**Issue by subproc** [copperhead/bugtracker#296]
i know that is not a security/privacy-related threat...but what about changing the default camera app that's a very poor app, with a snapdragon camera(but need of integrating some code aurora tweak) or with "open camera" from the fdroid repo?

**Comment by thestinger** [comment]
I don't want to make unnecessary changes, because it's too much to maintain. I'll then get bug reports about problems in that camera app, and I can no longer simply defer to AOSP. I won't be integrating CAF extensions into the base OS, as it would open up new security vulnerabilities that aren't in AOSP.
