### ISSUE TITLE
verified boot

### ISSUE THREAD

**Issue by subproc** [copperhead/bugtracker#298]
it's more a question that an issues....but why we need verified boot if it's telling us we have load a different os than the default whitout the possibility of knowing if we are using a tempered one?

**Comment by thestinger** [comment]
It can't be tampered with, because it prevents the key from being changed... that's the point of verified boot. The bootloader is informing you that a non-OEM key is being used, and it shows the fingerprint at the bottom. The fingerprint doesn't need to be verified for it to provide security, since the key can't be changed without unlocking the phone.

Regardless, this isn't part of CopperheadOS. It's a feature of the bootloader, which is not something that we can change or replace.
