### ISSUE TITLE
State of Nexus 5

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/bugtracker#300]
Hi

In the changelog of the latest release you wrote that you dropped support for pax for the deprecated Nexus 5. What does that mean? Does the new Release for hammerhead come without pax? Is the Nexus 5 nearing end of life?

**Comment by thestinger** [comment]
The Nexus 5 won't be getting Android N, so support will probably be dropped at that time. PaX was dropped because problems came up specific to the port to the old kernel version on the Nexus 5 (3.4), and time is no longer being spent resolving problems specific to the Nexus 5.

It would be possible to continue 6.0.1 security updates for the Nexus 5 after Android N comes out, but it's not looking like the project will have the resources to do that. There are still no contributors to the project, and very little money coming in.

**Comment by polyzen** [comment]
[ Issue 202974: 	Request: don't neglect Nexus 5 with more updates](https://code.google.com/p/android/issues/detail?id=202974)

**Comment by thestinger** [comment]
It's dropped entirely from CopperheadOS now.

**Comment by polyzen** [comment]
[Going Home - Fallen Soldier Bagpipe Tribute](https://www.youtube.com/watch?v=MR87LsmXzBs)

**Comment by vanitasvitae** [comment]
So no more monthly security updates?

I wanted to thank you very much for your hard work making Android phones more secure. I really hope that it pays out for you in the end  :)
Keep up the good work :+1:

**Comment by thestinger** [comment]
It's completely over now. No time to work on 32-bit / marshmallow-mr2-release anymore, and no spare build time to make builds for it even without testing / ongoing work.

**Comment by vanitasvitae** [comment]
I understand that :)
Will you support the upcoming pixel devices?
