### ISSUE TITLE
Camera preview fail after second start or switch between video and picture

### ISSUE THREAD

**Issue by acabrol** [copperhead/bugtracker#311]
On my Nexus 6P camera service works well after reboot but fail after camera app restart or switch between picture and video record.
I tried several camera apps like open camera I had the same issue.
The camera sometimes is able to take picture even if preview failed sometimes not at all.
Even force stop doesn't solve the issue only reboot solve it.
I guess is unavailability of camera device or service in the background which makes trouble.

**Comment by thestinger** [comment]
Needs logs from `adb logcat` to approach this, along with knowing whether you changed the advanced security settings in Settings -> Security.

**Comment by acabrol** [comment]
@thestinger you will find attached my log file with default camera app and open camera.
And screenshots of my security settings.
![screenshot_20160614-210156](https://cloud.githubusercontent.com/assets/14868902/16057356/02694682-327a-11e6-9d0e-992582c70475.png)
![screenshot_20160614-210206](https://cloud.githubusercontent.com/assets/14868902/16057359/0270888e-327a-11e6-8c2d-db0e6d085c12.png)
![screenshot_20160614-210218](https://cloud.githubusercontent.com/assets/14868902/16057357/026d8616-327a-11e6-8b23-540f99866a30.png)
![screenshot_20160614-210227](https://cloud.githubusercontent.com/assets/14868902/16057358/026f97c6-327a-11e6-9613-88eb1cb90626.png)
![screenshot_20160614-210232](https://cloud.githubusercontent.com/assets/14868902/16057360/0274f4b4-327a-11e6-91e1-2f0a565fe15f.png)

[nexus6pcamera.txt](https://github.com/copperhead/bugtracker/files/314822/nexus6pcamera.txt)

**Comment by thestinger** [comment]
This is the upstream issue filed as https://github.com/copperhead/bugtracker/issues/203. It's a memory corruption bug in Qualcomm's proprietary mm-qcamera-daemon uncovered by OpenBSD malloc. It's not feasible for us to fix the problem since we don't have the source code. Disabling page cache memory protection will *usually* avoid the segmentation faults when it tries to do the use-after-free but it's not a fix for the problem and it will still fault if it ends up being unmapped too soon regardless. It's memory corruption so it could cause all kinds of problems.

**Comment by acabrol** [comment]
I disabled page cache memory protection and camera apps works well now.
Thank you.
