### ISSUE TITLE
com.android.email crashes with com.android.exchange installed

### ISSUE THREAD

**Issue by moejoeblue** [copperhead/bugtracker#320]
Unfortunately I need to access mails on an Exchange server.

To use it on CopperheadOS I extraced com.android.exchange (6.0.1 5000065) from CyanogenMod 13 and installed it on a newly flashed Nexus 5X with CopperheadOS (MTC19V.2016.06.17.11.52.32).

When I try to launch the default E-Mail app, it crashes immediately.

If there is no way getting Exchange to work with the default E-Mail app, how can I also replace the default Mail app with the Mail app from CyanogenMod?

**Comment by thestinger** [comment]
CyanogenMod apps can't be expected to work outside of CyanogenMod. Exchange would still be included if Google hadn't removed it from the stable releases, but I don't want to revert that change. It could be because it has a security issue and since it's not maintained, they simply removed it instead of fixing the issue(s). Maybe it will be back in Android N, but either way it's a dead project with no more bug fixes since they migrated Exchange support to Play.

The solution is using an email client with Exchange support that's actually maintained, rather than the Android Open Source Project Email app which is a dead project along with Exchange, Calendar, Music, QuickSearchBox, etc.
