### ISSUE TITLE
bitmask

### ISSUE THREAD

**Issue by subproc** [copperhead/bugtracker#322]
how about integrating bitmask into copperhead os?

**Comment by thestinger** [comment]
We're not going to be bundling apps as a general rule, especially if they have no AOSP build system.

**Comment by thestinger** [comment]
If you want an app to be bundled, it has to have a fully contained AOSP build system first. No additional external dependencies. The inclusion of F-Droid has made CopperheadOS harder to build and reduces the cleanliness of the build system by requiring external dependencies. Bundling apps like Silence as binaries is no better, and then we become responsible for updating. It's not going to be done unless there are very good reasons for something to bundled rather than installed from F-Droid, as there were for those.
