### ISSUE TITLE
Improve UI / UX of the install documentation

### ISSUE THREAD

**Issue by bnvk** [copperhead/bugtracker#339]
A few ideas / thoughts I've come across during my process of flashing a device with Copperhead!
- [ ] Add styling to code blocks / commands like `fastboot flashing lock`
- [ ] Add numbers to each items `1. Prerequisites     2. Enabling OEM unlocking`
- [ ] Describe the process once `./flash-all.sh` completes what happens next (logos, encrypting device, etc...).
- [ ] Add a `Troubleshooting` section that talks about a few things that might go awry,  if one does not have enough RAM, if one reboots before the device encryption finishes!

**Comment by craftyguy** [comment]
I would take a shot at this if I could find the source for the install documentation on copperhead.co!

**Comment by darknetj** [comment]
@craftyguy I'll send you some information via email

**Comment by darknetj** [comment]
@bnvk still awaiting your acceptance and review

**Comment by bnvk** [comment]
> @bnvk still awaiting your acceptance and review 

Where do I review this? Is it is a repo here on Github or on the Bitbucket
somewhere? Perhaps i'm overlooking it, but I don't see anything!

**Comment by thestinger** [comment]
There have been some minor improvements to the installation guide over time and it's simpler now that the special cases for the Nexus 9 are gone (lacks full verified boot, uses `fastboot oem unlock` instead of the newer `fastboot flashing unlock`, etc.).

Issues involving styling beyond changes in pure markdown are a broader problem requiring a rewrite of the site. It doesn't make sense to keep building on the current broken foundation. It wasn't made in a maintainable / robust way so only the markdown content is important and worth working on. The rest needs to be thrown out and done from scratch, which isn't in the scope of documentation.

I don't think improving it is going to be a priority with Nexus devices on the way out. September 2018 is the end-of-life for the Nexus 5X and 6P at which point CopperheadOS will only be available as sources and preloaded devices unless something changes before then. The old model didn't work and I'm not able to keep maintaining the OS all on my own especially without being properly compensated for it which still isn't the case. We need to do everything we can to boost sales and not giving away official builds for free is definitely having a significant positive impact on that. I don't think enough people are building from source for that to have a significant negative impact, although you'd think that with ~30 people doing it we'd have gotten a contribution of code to the OS by now but nope - only the PDF Viewer app.
