### ISSUE TITLE
video recordings have green bar on left side on Nexus 5

### ISSUE THREAD

**Issue by o1y** [copperhead/bugtracker#344]
Recorded video files on the Nexus 5 have a green bar. The root cause is located in [Android.mk ](https://github.com/CopperheadOS/device_lge_hammerhead/blob/marshmallow-mr2-release/camera/QCamera2/stack/mm-camera-interface/Android.mk#L18-L20).

Replace the highlighted code with `LOCAL_CFLAGS += -DVENUS_PRESENT`, because util `is-board-platform-in-list` is not available in the code base.

**Comment by thestinger** [comment]
Has this issue been reported upstream? There are other calls to `is-board-platform-in-list`. It could be worked around on a case-by-case basis but if so I want to deal with all of them at the same time, and that doesn't seem like a great approach to this. Especially since more of these can creep in down the road for new devices, or simply enhancements to current generation devices (like the 5X and 6P in Android N).

**Comment by thestinger** [comment]
The necessary functions are now included: https://github.com/CopperheadOS/platform_build/commit/600d75d206caf20576880842d90bf5e40db0eb8d. It will be in the next release.
