### ISSUE TITLE
One-button build-from-scratch

### ISSUE THREAD

**Issue by kckrinke** [copperhead/bugtracker#376]
Not sure of the merit but I believe it to be of importance. One of the tenants of fruitful community-driven projects is the "one button build". If a build takes more than one button to build, it's much harder for non-project-devs to get involved.

Using docker to setup, fetch, pull, organize, build, and so on is one option for example.

**Comment by thestinger** [comment]
Support for multiple targets complicates this. There needs to be a step for choosing the build target and build type (release vs. debug, user vs. userdebug vs. eng). Devices also have their own branches in some cases, rather than them being built from the same source tree.

**Comment by thestinger** [comment]
I don't think this is the barrier to people contributing. Lots of people are building CopperheadOS, but no one is contributing anything. I don't plan on investing any more time into making it easier for people, since we're not getting anything in return. Even if someone else implements this, I won't want to maintain it. Simpler is better.
