### ISSUE TITLE
OTA updater progress not displayed

### ISSUE THREAD

**Issue by pnelson** [copperhead/bugtracker#421]
I'd like the progress of the download to be displayed on the updater notification.

I'm not intimately familiar with the Android ecosystem but it looks like a standard downloader notification. Progress is displayed for most other downloads, but never the OTA update. I assumed a missing Content-Length header but [this](https://github.com/copperhead/android_ota_manager/blob/master/controllers/files_controller.go#L28) should take care of that for you. I didn't check the network. Is there another reason this isn't displayed?

**Comment by thestinger** [comment]
The OTA updater does display the progress bar. The current hosting for our updates results in Content-Length being stripped out. It's something that's out of our control. OpenShift has a buggy implementation of *mandatory* gzip compression for response, and they have no opt-out since they don't respect no-transform.

**Comment by thestinger** [comment]
This might be fixed when we eventually migrate to the new OpenShift platform version. It's not something that we're going to keep an eye on though. Once it starts working at some point, we can try to prevent it from regressing.
