### ISSUE TITLE
Add hammerhead images back to download page

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/bugtracker#425]
Hi!
I understand, that hammerhead builds are deprecated, but why did you remove them from the download page at all, when they are in fact still downloadable?

I personally apply system updates via adb sideload and used to download the images from your download page. Now I have to find out the full image name with date and time from Copperheads system updater app and manually enter the download address on your site in my web browser to get the image.

Please add an option to show hammerhead updates on your download site.

**Comment by thestinger** [comment]
It was removed from the downloads page because it's not supported anymore and we don't want people installing it with the expectation of support and continued updates, even though we're still going to be releasing the remaining security updates. The last guaranteed security update is October 2016, i.e. next month. The Nexus 7 (2013) was dropped by Google this month after the guarantee ended in August, so it only got one extra month of support, so we do not expect Nexus 5 support to continue much longer.

As soon as there's a security update that it does not receive, we will be completely removing the downloads for it. That will probably happen in November or December.

FWIW, you can obtain the information from https://builds.copperhead.co.

We aren't going to be making any changes to Nexus 5 support at this point, including to the site. Continued security updates were not necessarily going to happen at all but we decided to do it since it's not going to be for much longer anyway.
