### ISSUE TITLE
CopperheadOS updater crashes, can't download updates

### ISSUE THREAD

**Issue by Rudd-O** [copperhead/bugtracker#427]
After I start the download, it "downloads" for like a minute, then it closes and then I get asked to restart it.

**Comment by pnelson** [comment]
I had a similar issue after the September 5th update to Nougat. Mine would download the whole update and crash when trying to save. I had a ton of other issues though, alarm sounds disappeared, stock email client couldn't open emails, etc.

This is what I saw in logcat when the download completed:

```
09-08 18:04:47.290 22959 23242 E AndroidRuntime: FATAL EXCEPTION: IntentService[DownloadCompleteIntentService]
09-08 18:04:47.290 22959 23242 E AndroidRuntime: Process: com.cyanogenmod.updater, PID: 22959
09-08 18:04:47.290 22959 23242 E AndroidRuntime: java.lang.SecurityException: COLUMN_LOCAL_FILENAME is deprecated; use ContentResolver.openFileDescriptor() instead
09-08 18:04:47.290 22959 23242 E AndroidRuntime: 	at android.app.DownloadManager$CursorTranslator.getString(DownloadManager.java:1499)
09-08 18:04:47.290 22959 23242 E AndroidRuntime: 	at com.cyanogenmod.updater.service.DownloadCompleteIntentService.fetchDownloadPartialPath(DownloadCompleteIntentService.java:121)
09-08 18:04:47.290 22959 23242 E AndroidRuntime: 	at com.cyanogenmod.updater.service.DownloadCompleteIntentService.onHandleIntent(DownloadCompleteIntentService.java:66)
09-08 18:04:47.290 22959 23242 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
09-08 18:04:47.290 22959 23242 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-08 18:04:47.290 22959 23242 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-08 18:04:47.290 22959 23242 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

I ended up sideloading the September 7th update and everything worked fine after. I'm getting the same issue for today's update though.

**Comment by thestinger** [comment]
This is a known issue with a workaround available. See https://twitter.com/CopperheadOS/status/773547201083629568.

**Comment by thestinger** [comment]
@pnelson Delete the update and download it again. The download was either corrupt, or your device failed to reboot. It's not possible to attempt to install an update a second time without downloading it again. You can hold power and press volume up at the recovery error screen to see the error message. It's probably a signature validation failure, since you're attempting to install it a second time which mangles it. The AOSP update installing system simply doesn't support that.

**Comment by thestinger** [comment]
We will try to fix the Nexus 5X reboot-to-recovery issue at some point. We've tried before, but with no luck. The initial Nougat Updater app problem was unfortunate, but fortunately it's possible to update either by install the fixed Updater.apk which I made available for independent installation or by sideloading the update instead of doing it over-the-air.

**Comment by thestinger** [comment]
See https://github.com/copperhead/bugtracker/issues/285 for that 5X issue.
