### ISSUE TITLE
Tethering doesn't work on 6P because of missing vendor app

### ISSUE THREAD

**Issue by jmndn** [copperhead/bugtracker#434]
Build: NRD90U.2016.9.14.05.23.28
Device: Nexus 6P
Description: Tethering is grayed out in settings and can't be activated by the hotspot quick settings widget. The bug seems to happen because com.huawei.entitlement is not included in this build, causing the entitlement check to fail.

[Relevant logs (generated on tapping hotspot widget)](https://github.com/copperhead/bugtracker/files/475627/logcat.txt)

**Comment by thestinger** [comment]
I'm not going to include the Entitlement app for this, since it's not inherently needed. The workaround that was used before might still work, but it's possible that something new is required. It's a very low priority, so if people want this to work again they should figure this out, test it and submit a patch.

**Comment by thestinger** [comment]
Tethering provisioning is disabled again. Let me know if any issues come up.
