### ISSUE TITLE
conversations app crashing on N build

### ISSUE THREAD

**Issue by canary5** [copperhead/bugtracker#443]
Not sure if its app or N problem, just added you a log to take a look.
http://pastebin.com/8BFsQAcP

**Comment by thestinger** [comment]
Please try again with the latest Conversations and CopperheadOS.

**Comment by canary5** [comment]
I have tested both latest latest versions but still crashing just afyer boot. But later working good. Crashing first run. But noticed some strange thing, if i reboot without internet connection(just wifi off dont have mobile) its not crashing

**Comment by rosswell98** [comment]
I have the same problem, but I don't thinks that it's directly related to Conversations.
When peoples talk with me, I can reply without problem in the notifications center, the problem appears when I want to open Conversations.

**Comment by thestinger** [comment]
Check if this is still present with NRD90U.2016.09.27.15.19.19, there are some relevant compatibility fixes.

**Comment by canary5** [comment]
Still same crash at the restart

**Comment by rosswell98** [comment]
For the moment I had no crash with the latest update...

**Comment by canary5** [comment]
Try reboot your phone. Just after reboot click on conversation icon

**Comment by rosswell98** [comment]
I just rebooted now, tried, and I had no problem...
Did you tried to clean the Conversations cache ?

**Comment by canary5** [comment]
I will do clean install today

**Comment by rosswell98** [comment]
Don't, ignore my last comment, I had the problem like 1 hour after my response...

**Comment by rosswell98** [comment]
Conversations 1.14.3 is out on F-Droid did you installed it?
In the changelog:
"Version 1.14.3
***
fix rare start up crashes"

**Comment by rosswell98** [comment]
The issue is always here...
I don't think thats a CopperheadOS issue...

**Comment by canary5** [comment]
I have tested on another N system. No crash, so its copperhead issue it think. I opened ticked on conversations. But they doubt its conversations issue as well

**Comment by rosswell98** [comment]
I see. The issue is confirmed... Conversation can be openned after 2-3 tries, just wait for the fix...

**Comment by lagosazules** [comment]
Still no ETA for this fix? It is very annoying this CopperheadOS bug, Conversations is in my opinion one of the most important application, hope for a quick solucion.

**Comment by thestinger** [comment]
ETA == when one of you feels like contributing a fix for it.

**Comment by thestinger** [comment]
It's probably caused by exec spawning. Step one: make a build without exec spawning. Revert 514fe7f117db62704d8759d83c27ad8fc3ccbf8b and eb00f8dff5dfb4ac080540a9179dca30b48cca28 (in that order).

If that doesn't work, revert b8d123b8554f34cfea46148b248c84e9ecd190e5 and then fa54c344d37380414e1cab5d037fe10301e6d38b in that order too. If that works, revert the eb00f8dff5dfb4ac080540a9179dca30b48cca28 revert then the 514fe7f117db62704d8759d83c27ad8fc3ccbf8b revert to determine if enabling preloading while still using exec spawning fixes it.

That's the easy part. Assuming one of those things is the cause, figure out *why* it happens. Doing that kind of thing will often take days of work or more. Can use a debugger, strace, perf trace, etc. It seems to be a race, so setting affinity to pin to a single core might help with debugging. Maybe it's something that TSan could figure out but I doubt it.

**Comment by thestinger** [comment]
Not planning on working on it though. It seems like an AOSP or app bug uncovered by exec spawning. So I need evidence it's a CopperheadOS bug to devote my limited time to working on it. That's how this works.

**Comment by thestinger** [comment]
In my experience, people start contributing to projects by fixing issues that annoy them. So I plan on working on under the hood stuff that's not incredibly annoying to leave the door wide open to contributors. If people finally start contributing, it's going to be because there's stuff like this to figure out. On the other hand, no one is going to step up to fix one of the memory corruption bugs caught by our mitigations while running the Compatibility Test Suite. Someone might complain about a "random" reboot now and then, but that won't go anywhere.

**Comment by lagosazules** [comment]
I do understand and respect your choice, sorry I can't help to find this bug, you are realy doing a great job but I think what to do with this N version and have to use one of the best and only xmpp onemo interfaces with this bug? Copperhead needs the use of the most secure apps and Conversations is one of them.

**Comment by iNPUTmice** [comment]
I created a Conversations branch that might have a work around (not a fix) for this.
I'd be interested to know if this works https://github.com/siacs/Conversations/tree/possible_copperhead_fixes

**Comment by lagosazules** [comment]
I do not have a 5x at this moment to check it out, thanks for your work on this, it looks like no one is using a CopperheadOS Conversations combination.

**Comment by canary5** [comment]
Hi. Its still crashing for me. I just tested this build. Thanks a lot for your efforts

**Comment by rosswell98** [comment]
I have a N5X, with CopperheadOS and Conversations.
Since last update (of CopperheadOS)  I had no crashes for now...

**Comment by thestinger** [comment]
The issue is still present. It's a race condition. I need someone to spend time working on it, not testing to see if it's present (it is).

**Comment by thestinger** [comment]
A workaround for this AOSP bug is in today's release.

**Comment by thestinger** [comment]
The AOSP bug is not fixed so this will remain open to track that, along with the removal of the workaround.

**Comment by lagosazules** [comment]
Working fine, Thanks Copperhead team !

**Comment by canary5** [comment]
Thanks a lot, great work!

**Comment by thestinger** [comment]
Replacing this issue with #491.

**Comment by thestinger** [comment]
@iNPUTmice Google finally fixed this in https://android.googlesource.com/platform/frameworks/base/+/e2179925df2ce174d81dd6f7abae626cc859ce00.
