### ISSUE TITLE
some problems after last update

### ISSUE THREAD

**Issue by canary5** [copperhead/bugtracker#486]
I have some laging sometimes mostly using chronium. Today it even was freezed. Logs of the freeze:

www.pastebin.com/rmWKfB4R

**Comment by thestinger** [comment]
We ship Chromium unmodified and it was updated in the last release. We're not going to track every Chromium bug here.

It's also known that app spawning is going to be slower because preloadResources had to be added back. If someone wants back that 100ms of app spawning performance they can contribute a fix for the upstream bug(s) that had to be worked around by doing that.

**Comment by canary5** [comment]
Ok thanks for the info

**Comment by thestinger** [comment]
There will be another release with a Chromium update in the next few days with more upstream bug fixes, FWIW.

**Comment by Vodochnik** [comment]
Hi canary5, how can i contact you?
