### ISSUE TITLE
Encryption Password Not Set Separately on Nexus 5X

### ISSUE THREAD

**Issue by Fscked-In-The-Head** [copperhead/bugtracker#517]
With the two builds currently available on the Copperhead.co website (2016-11-21 and 2016-11-27), the encryption password cannot be set from the Security section in the Settings menu. Under Encryption it just says Encrypted.

I've tried multiple clean flashes, and even tried flashing the stock image first. Everything else seems to work fine, but there is never an opportunity to set the encryption password.

**Comment by thestinger** [comment]
The option of setting a separate encryption password hasn't been reimplemented since the port to Nougat, because it's not compatible with the new file-based encryption format. See https://github.com/copperhead/bugtracker/issues/451 for the planned replacement. So far, no one has been interested in working on it so it hasn't happened.
