### ISSUE TITLE
Get gesture typing working for AOSP Keyboard

### ISSUE THREAD

**Issue by Sortova** [copperhead/bugtracker#532]
Are there any plans to get gesture typing working on the AOSP keyboard that ships with Copperhead?

In searching for a solution, it looks like a non-free library may be needed, but I'm not sure this is the case.

Basically, if you go under Settings -> Language & input -> Virtual keyboard -> Android keyboard -> Gesture typing you'll see that "Enable gesture typing" is selected but it doesn't work.

**Comment by thestinger** [comment]
There's no usable implementation of gesture typing. The AOSP keyboard is an abandoned project so there isn't going to be any further progress on it. The voice input and gesture typing options have been hidden in the development branch since they were only there for the extended Google Keyboard built from the AOSP Keyboard and that app is now dead, thus there's no maintenance of AOSP Keyboard.

**Comment by thestinger** [comment]
If the open-source community makes a better keyboard than AOSP Keyboard, we'll switch to it. Right now it's still the best option. There's no choice available with gesture typing, let alone parity with the usability of the built-in keyboard. Copperhead isn't going to be developing a keyboard. It's totally out of scope for the project.

**Comment by Sortova** [comment]
Got it.
