### ISSUE TITLE
option to disable emergency calls when using FBE

### ISSUE THREAD

**Issue by e-lektryk** [copperhead/bugtracker#549]
Even when phone is locked rogue person could trigger call to some emergency number. It may be used to trigger some communication to false BTS for future exploitation.
I do not know if it is required by law, so maybe it should be configurable with default turned on.

**Comment by thestinger** [comment]
It's required by law in many regions and that screen is before user data is available. It's not possible to disable it with FDE. It could be disabled only with FBE.

**Comment by sigenc** [comment]
Hi,

this is something i consider really important. Same as [#460](https://github.com/copperhead/bugtracker/issues/460). There should also be the possibility to run copperheados only in WIFI. So there are no possible attacks on baseband or sim. For example like if you run an ipod.

**Comment by thestinger** [comment]
Feel free to work on either of them then. It isn't going to happen at all without anyone working on it.

**Comment by sigenc** [comment]
I can't work on them at the moment. There is no time left and i think you have some more important stuff to do. But i will setup a bounty for this.

What we need is:

- complete baseband isolation, so only wifi works. (As for what i know physically cutting the baseband antenna doesn't work)
- option to hide QuickSettings from Lockscreen (This is already possible in AOSP for Nexus 5)
- dead man switch
- safer wifi management

**Comment by darknetj** [comment]
@sigenc thanks for your feedback!

As it stands, we're not interested in facilitating placing Copperhead resources on features from non-paying users. We're tapped out as is.

Also: It looks to me that you're interested in developing a product based on CopperheadOS that has certain requirements in it - I know this because what you're asking for is a common ask amongst our commercial partners. If this is true, it's prudent to reach out to me via email (team@copperhead.co) and begin discussing official CopperheadOS licensing of your product. If this isn't true then you're going to have to wait for someone to develop these requirements on their own free time, which from our experience, won't happen.

**Comment by thestinger** [comment]
This isn't currently planned since I don't think it would be legal.

**Comment by sigenc** [comment]
What? Why should it not be legal? So every device similar to a phone but without a modem should be illegal. The ipod should be illegal. Osmocom should be illegal, cause you can turn of the modem. Same as the Neo900. It is not illegal.

**Comment by thestinger** [comment]
This isn't the place the debate whether laws / regulations make sense. It's irrelevant. Since we sell phones in Canada and the US we need to conform to their laws. We're going to need to respect EU laws too.

If we sold phones to India, we would need to make sure https://source.android.com/devices/tech/connect/emergency-affordance is enabled too.

**Comment by thestinger** [comment]
It's possible that we're already not conforming to regulations in some countries by preventing toggling off Airplane mode from the lockscreen if the phone is locked. However, that's likely not explicitly forbidden so it's less of a problem.

**Comment by sigenc** [comment]
Thanks for the link. I will have to research this. Cause this would mean every device with a baseband modem should always be in a state where it could connect to a BTS. So no way of seperating the modem with a toggle. This is something i'm not quite sure about. Cause one of the bigger security firms in Germany, have a toggle for the modem. And they are selling worldwide. USA, Canada, EU and eastern part of the world. You can complete diasble the modem acces with their rom. So even no emergency calls. By the way, they are very good at hardening android and have the first usefull baseband firewall. http://www.cryptophone.de/en/

**Comment by thestinger** [comment]
A hardware switch could be flipped even when the phone is locked.

**Comment by thestinger** [comment]
> You can completly diasble the modem acces with their rom. So even no emergency calls. 

There isn't a physical switch on Nexus / Pixel phones but Airplane mode does do that.

**Comment by thestinger** [comment]
I don't think it's productive to discuss this further. It's ending up on completely unrelated topics.
