### ISSUE TITLE
Custom certificates for whole copperhead os

### ISSUE THREAD

**Issue by e-lektryk** [copperhead/bugtracker#550]
It would be nice feature to have a simple tool to "generate" whole system signed with custom (stored localy at user premises) certificates, just for case when copperhead company certificates were leaked or requested by government agency.

**Comment by thestinger** [comment]
You have this option: build the operating system. Building it is straightforward and well documented. The tools to resign it from the AOSP test keys exist and are built as part of building the OS. More than that isn't going to be provided. For some time we published the target files zip in case anyone wanted to resign it with those tools but there was no interest and it's not going to be published again because the target files zips are too big for us to upload and host them. Unless someone is going to pay to run fibre here and pay for a dedicated server with lots of space.
