### ISSUE TITLE
No cellular data, T-Mobile, Nexus 6p

### ISSUE THREAD

**Issue by kittenpirate** [copperhead/bugtracker#580]
Cellular data will not connect unless ipv6 is changed to ipv4 in the APN settings. This issue was reported in #340 and closed but I disagree and think it should remain open. It seems to be caused by copperhead as this issue does not occur in other ROMs.

For anyone willing to debug this, with the phone using default APN settings, It should be noted that if "cellular data always active" is toggled on, the cellular data will connect when the wifi connects. Otherwise it won't work. It will not stay connected however, and requires finding wifi to force it again.

**Comment by thestinger** [comment]
I'm not going to keep open carrier bugs that we can't reproduce and that aren't demonstrated to be CopperheadOS issues. Bugs need to be reproducible in order to maintain the tracker. This working elsewhere doesn't mean that it's caused by CopperheadOS. It might occur with the same subset of the vendor files used with AOSP, and there are reasons for restricting it to the subset that's used. The only way this is going to be kept open as an issue is if someone builds AOSP with the same vendor files repository and confirms that this *doesn't* occur there and then works on debugging it by disabling features until it works. There are some obvious things to try: reverting the system/netd changes and reverting the TCP/IP stack hardening in system/core (the /proc/sys writes).

**Comment by kittenpirate** [comment]
Are you using a T-Mobile SIM card and a Nexus 6P to try and reproduce the bug? There have been a lot of complaints about this very issue with this combination of variables. If the cellular data never worked using ipv6, that would be one thing, but toggling "cellular data always active" will force it to work when wifi is connected. That leads me to believe it's a copperhead bug.

**Comment by thestinger** [comment]
T-Mobile doesn't exist here. There will be no reproducing it on our end. It could simply be that CNEService or something else needs to be included. That doesn't make it a CopperheadOS bug, since those are not included in AOSP or their binary releases for AOSP. No one has demonstrated that this doesn't occur with AOSP built with the same set of vendor files.

**Comment by kittenpirate** [comment]
Ok. I'm not technically trained enough to, as you put it:

"...builds AOSP with the same vendor files repository and confirms that this doesn't occur there and then works on debugging it by disabling features until it works."

Maybe you are. Maybe that's why I posting here.

**Comment by kittenpirate** [comment]
I do not know how to, as you put it:

"..builds AOSP with the same vendor files repository and confirms that this doesn't occur there and then works on debugging it by disabling features until it works."

If I was, I wouldn't be posting here asking for your help. It seems like you posses the skills to troubleshoot this. It can't be that hard to get your hands on a T-Mobile sim card.

**Comment by thestinger** [comment]
As I said, T-Mobile doesn't exist here. It's a US carrier issue and Copperhead isn't based in the US. I also expect that this is simply an AOSP issue occurring with android-prepare-vendor. It's possible it's related to the minor network changes and it would be easy enough for someone with access to T-Mobile to determine that by just reverting the netd firewall changes and the ip sysctl changes in system/core.

**Comment by kittenpirate** [comment]
I guess I better start teaching myself how to do that.
