### ISSUE TITLE
Switch to Iridium browser

### ISSUE THREAD

**Issue by spacekitteh** [copperhead/bugtracker#593]
[Iridium](https://iridiumbrowser.de/index.html#about) is a hardened version of Chromium. It must be investigated whether the changes carry over to the android webview.

**Comment by thestinger** [comment]
It's not properly maintained: it's still on Chromium 54, and Chromium is up to version 56 for stable, so it's missing a bunch of security updates. I don't really think they have any useful changes for us anyway since we already make Chromium changes: https://github.com/CopperheadOS/chromium_patches. Brave's Android browser has more interesting stuff to potentially borrow but I wouldn't actually want to switch.
