### ISSUE TITLE
Have option to restrict apps from using camera, microfon, .. when phone is locked

### ISSUE THREAD

**Issue by loki-sama** [copperhead/bugtracker#606]
Like an off switch for parts of the phone. To ensure that the phone is not usable as listening device. 
Ty for the great work!!!

**Comment by thestinger** [comment]
I think it makes more sense to start with toggles to be based on whether the app is currently is in the foreground: https://github.com/copperhead/bugtracker/issues/635 https://github.com/copperhead/bugtracker/issues/636 https://github.com/copperhead/bugtracker/issues/637 https://github.com/copperhead/bugtracker/issues/638.

Of course, no progress is going to be made on any of these planned features without anyone willing to contribute or a promising candidate to hire to work on them. Since we don't have contributors to the OS itself, there isn't really a pool of prospective people to contract out this kind of development.
