### ISSUE TITLE
Nexus 6P random reboot

### ISSUE THREAD

**Issue by sigenc** [copperhead/bugtracker#613]
I just noticed i have the same Problem with random reboot. Just watched my Phone reboot before my eyes. I installed yesterday the update via the updater in cos. Phone worked without a Problem for 12 hours. 

Build : N2G47J.2017.04.04.01.07.02

Edit: noticed this here in another issue:

>  It's likely not actually rebooting but rather just going back to the boot logo. If you aren't seeing the Google logo and the verified boot notification screen again, it's not actually a reboot.

This happened right now. No Google logo, but i saw the cos logo spinning... I will try to get the log later.

Some additional Information.

- the device is without a sim card
- airplane mode is active
- wifi is active
- it is connected to a network
- the device was not used at the moment -> locked
- international 32 GB Nexus 6P version

**Comment by thestinger** [comment]
Yeah if it just went back to the logo, that means one of the core services crashed so it restarts them, but it didn't actually reboot. That means it's possible to get `adb logcat` logs.

**Comment by thestinger** [comment]
Seems to be the same issue as #613. This is likely an upstream bug which I haven't fixed, but I tweaked junk filling to be less aggressive in production builds by using zero filling to stop uncovering as many upstream bugs in production instead of just mitigating exploits and papering over bugs with zeroing vs. values that will cause pointer usage to fault. Logs would be helpful. I can't keep issues open without a way to replicate the problem and without logs / other debugging happening.
