### ISSUE TITLE
On removal of proprietary blobs

### ISSUE THREAD

**Issue by SpotComms** [copperhead/bugtracker#624]
If there was a universal build-time script that was able to successfully remove a large portion of the device proprietary blobs without impacting core functionality in anyway, would such a script be considered to become part of the official releases? It'd be basically this https://github.com/copperhead/android-prepare-vendor/commit/ea4b42c617991607970471f6eee2615f29570dc4 but to a much larger extent.

**Comment by thestinger** [comment]
Patches removing / replacing unnecessary closed-source SoC vendor code for the Pixel and Pixel XL would be accepted if they're clean, robust and well-tested. A fair bit of the "proprietary blobs" are really open-source code that can be built from Qualcomm sources, but it needs to be certain that the sources are identical to the ones used by Google, which is difficult.

On the other hand, this ship has sailed for the Nexus 9, Nexus 5X and Nexus 6P. It's too late to propose this kind of device-specific work for those devices as we don't want to deal with the fallout for anything but current generation devices.

Changes also won't be accepted unless they're relevant to CopperheadOS. Code for derivatives of CopperheadOS isn't going to be maintained by us as part of CopperheadOS itself. It should be maintained by the people using it, particularly since they aren't currently contributing anything back to CopperheadOS.
