### ISSUE TITLE
editing build.prop

### ISSUE THREAD

**Issue by hajzso** [copperhead/bugtracker#631]
Hi, this is not really an issue with Copperhead, (loving it) more like an issue with me, so bear with me please.. :) I am using LMT Launcher for pie controls, and I would like to hide the softkeys. If you have superuser (which I don't want to have) this is done by editing the build.prop file and changing qemu.hw.mainkeys=0 to 1. 

Am I right to assume that the only way to do this is to build the system for myself and edit it before? Is there any other way? (like downloading a build and editing it somehow, then skipping verification?) Could someone point me in the right direction on how to do this?

**Comment by thestinger** [comment]
I don't know exactly what you mean by softkeys but that's not really important.

You can't edit boot/recovery/system/vendor because they're signed for verified boot. The update packages have signature verification too. If you want to modify the OS, the simplest way to do that is making your own builds. Otherwise, you'll need a way of making your modifications and then signing all of the images and the update packages / factory images again. At least if you don't want to reduce security by leaving your bootloader unlocked, disabling dm-verity and disabling the update signature checks. Note that leaving the bootloader unlocked means not having verified boot so it reduces more than just physical security, as would not performing update signature checks. You also wouldn't be able to use our updates anymore without modifying them in the same way each time.

**Comment by hajzso** [comment]
Thanks for the quick help! By softkeys I meant software keys, or the navigation bar at the bottom. (back, home, recentapps) 

For anyone using pie controls: I found a temporary workaround, enabling global immersive mode in adb:
`adb shell settings put global policy_control immersive.navigation=*`

The only problem with this is when using the keyboard, the navbar still pops up. I'll see how much it bothers me and might look into making my own builds.
