### ISSUE TITLE
Is Noise violating the GPL?

### ISSUE THREAD

**Issue by vn971** [copperhead/bugtracker#632]
The Copperhead OS repository has 4.6.0-1, and the source link points to https://github.com/copperhead/Noise

There are no sources for 4.6.0-1 to be seen though. Where can I find them? Or what is the issue behind this?

Thank you

**Comment by thestinger** [comment]
The GPL doesn't require that sources are made available to the public. It requires that they be made available to users upon request. For example, grsecurity is a derivative of a GPL2 project (Linux) but the sources are not made available to the public anymore which is not a GPL violation.

Rather than making a baseless legal allegation, you could have simply mentioned that we forgot to the push the 4.6.0 branch... which is now done.

**Comment by vn971** [comment]
@thestinger No hard feelings, the issue title was a question. I just had a discussion and forgot to properly re-word the question. Sorry.
Thanks.
`grsecurity` is a different beast in that it doesn't publicly share binaries (if I understand it correctly), and Copperhead repo does.

**Comment by thestinger** [comment]
Regardless of whatever differences you think there are from that example, your understanding of the GPL is still wrong, and you came here making an accusation based on that misunderstanding.
