### ISSUE TITLE
Need license for Pixel XL

### ISSUE THREAD

**Issue by Rudd-O** [copperhead/bugtracker#634]
I need to test Pixel XL works with CopperheadOS but the download isn't available.  Where and how can I arrange for a license?  Thank you in advance.

**Comment by thestinger** [comment]
We haven't started selling licenses for the official builds yet. It can be built from source though.

**Comment by thestinger** [comment]
You can contact sales@copperhead.co but we just haven't started doing this yet. Can build from source or buy a device with it preinstalled today, but not a license for official builds on a device + access to them.

**Comment by Rudd-O** [comment]
:-\ that's quite disappointing.  I was ready to shell out the cash.  I contacted sales@ and I am waiting for a reply.

**Comment by thestinger** [comment]
There's very limited time to go around and we haven't had time to set up selling licenses for official builds, only selling devices with the OS.

**Comment by Rudd-O** [comment]
What's the ETA in any case?  I need to see if I should return the device and give up.

On June 7, 2017 7:23:00 PM GMT+02:00, Daniel Micay <notifications@github.com> wrote:
>There's very limited time to go around and we haven't had time to set
>up selling licenses for official builds, only selling devices with the
>OS.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/copperhead/bugtracker/issues/634#issuecomment-306865466

--

Rudd-O

http://rudd-o.com/

**Comment by thestinger** [comment]
I don't have an ETA. If there was someone who could dedicate time to that, it could get done in a few days. Unfortunately, CopperheadOS is currently essentially two people, one handling the whole technical side (OS maintenance, porting to new versions, development of new features, testing, debugging, system administration and maintenance of the services / site) and one handling the entire business side. There's someone else doing contract work for us on the side but it's to bring in income and isn't really CopperheadOS itself. I think that makes it clear why we cannot get everything done regardless of how high priority users think it should be. There cannot be an ETA for most things either. If time can be found to do something it can get done.

**Comment by Rudd-O** [comment]
OK.  What do you need?
--

Rudd-O

http://rudd-o.com/

**Comment by thestinger** [comment]
I don't know. All we have right now is a manual username/password system for access to the images. There needs to be a system for selling them and getting people onto the support system. That's not really my area. I can't tell you exactly what is needed. I don't know the laws in various countries that apply to selling licenses of software like this or how taxes are supposed to work. It's much less trivial to do this than people think. Are we allowed to sell software in say Germany without charging people tax and paying it to their government? I have no idea, and there are many countries with their own rules.

The intention is for a license to be needed for each device which is another issue as someone could buy one license and reuse it any number of times including to sell devices. We've had problems with companies breaking the terms of our licenses for official builds for the Nexus 5X/6P and the terms of source code license.

**Comment by thestinger** [comment]
If we need to charge tax and pay it to various countries, then we can't realistically sell to people in those countries. It's too much of a complicated. We aren't able to deal with that. Selling phones is means the taxes can get paid as part of the shipping costs.

**Comment by thestinger** [comment]
> The intention is for a license to be needed for each device which is another issue as someone could buy one license and reuse it any number of times including to sell devices. We've had problems with companies breaking the terms of our licenses for official builds for the Nexus 5X/6P and the terms of source code license.

And since we aren't going to implement any kind of DRM nonsense, we'd need to decide if this is worth it. It would be a major problem if we had comparable load on the Pixel update server as we do for Nexus devices because it doesn't have Cloudflare in front as a caching CDN. Cloudflare bugs prevent that.

**Comment by Rudd-O** [comment]
Tricky problems to solve — I fully understand your predicament.  Are there online shop software packages that can take care of the regs problem of the equation?  Maybe it's better to target the U.S. market exclusively to start with? How does the license get tied uniquely to a device?  Can the device request the software update with a specific unique-to-device parameter or challenge-response?  Will this require per-device builds?  All tough questions not normally needed to be solved in the OEM model.
--

Rudd-O

http://rudd-o.com/

**Comment by thestinger** [comment]
There's no DRM. If we sold access to the images, we would be relying on the honor system in terms of people not reusing them for multiple devices. People also rightfully need to be able to replace a broken device and flash the images onto the new one if we sell software licenses rather than hardware. I don't think people would like it if we reported something like an IMEI to the update server, and it's a bit late for that since we've already sold Pixel phones that are downloading updates from our server automatically. I don't think we can decide that it requires authentication without having a second update server and a whole second set of builds. I can't see that happening.

I think we would need to stick to targeting the US and Canada to start and hopefully there aren't taxes to deal with for the US.

I'm not sure that we will sell licenses for Pixels. I'm not sure if we'll ever do it. It will likely only take a few days to set up but there are a lot of unanswered questions and we aren't really getting any closer to answering them. Copperhead has very limited resources. We just can't get everything done and there this license selling thing is far more complicated than it seems.

**Comment by thestinger** [comment]
It's also worth noting that if we sold images, someone uploaded one to the thepiratebay.org and many people flashed it, our update server would be quickly overloaded and customers would be impacted. It only takes someone uploading *one* version of the images for that line to be crossed forever, since they can update to the newest version from there. Our new update server cannot take much load because it doesn't use Cloudflare, because Cloudflare breaks resuming downloads.
