### ISSUE TITLE
Nexus OTA Updater does not check if $new_version > $old_version

### ISSUE THREAD

**Issue by jadoro** [copperhead/bugtracker#713]
My Nexus 5X just asked me to install updates – available were
* bullhead-2017.08.21.*
* bullhead-incremental-2017.08.14.*

I went with `2017.08.21.*` first, as I thought the more recent image will include old updates. Installing the update worked, however: `bullhead-incremental-2017.08.14.*` is still shown as available update.
If one tries to install it, the Updater does not recognize that the phone's version is actually newer. The process fails somewhere in Recovery mode.

Failing in recovery mode is a bit late imho, I would much prefer if
* old updates are no longer shown as available
* trying to install old updates fails early

**Comment by thestinger** [comment]
The legacy updater isn't going to receive any substantial changes anymore. https://github.com/CopperheadOS/platform_packages_apps_Updater is the modern updater and works much better. It resumes downloads that are interrupted, performs downgrade checks (by necessity since recovery isn't there to do it), works fully in the background without the user needing to manage updates at all, etc.

**Comment by jadoro** [comment]
Thanks for your explanation.
Is the new updater designed for usage on the Nexus devices?

**Comment by thestinger** [comment]
It currently only targets devices with support for A/B updates but we have a pending change to make it work for devices with the legacy update infrastructure. However, we lack the resources to deploy it.
