### ISSUE TITLE
System Updates settings applet is absent

### ISSUE THREAD

**Issue by Rudd-O** [copperhead/bugtracker#846]
For the past few builds I've made, the Updater app settings is absent and I cannot trigger an update check.  Why is that happening?

**Comment by thestinger** [comment]
The Updater package is only included if `OFFICIAL_BUILD` is set to true in the environment. You either need to `export OFFICIAL_BUILD=true` after pointing it at your own update server or you need to unconditionally add the `Updater` package.

That's done because people kept making unofficial builds with the `Updater` app pointed at our server so it was wasting a bunch of our resources and their data / battery life without them realizing it.

**Comment by thestinger** [comment]
Look for `OFFICIAL_BUILD` in device/google/marlin or the relevant device repository.

**Comment by Rudd-O** [comment]
OK.  Thanks.

**Comment by Rudd-O** [comment]
https://github.com/Rudd-O/copperheados-build/commit/d7341b9c6346017d9a0d38b7594e9ed39b3777a9 is where this was implemented.
