### ISSUE TITLE
Web search of selected text in apps uses Google

### ISSUE THREAD

**Issue by mople71** [copperhead/bugtracker#860]
Selected text in an e-mail, tapped *WEB SEARCH* and was rather surprised as Google.com opened in the web browser. 

I don't know whether it's per-app or can be somehow set globally. Works as expected &ndash; using DuckDuckGo &ndash; in Chromium.

If it's per-app, would you please at least enforce using DuckDuckGo in PDF Viewer and the e-mail client?

**Comment by thestinger** [comment]
It's determined by the Search app, not the browser or the apps running searches. The Email and Search apps are both dead projects with only security fixes applied. Neither is a useful starting point for new apps.

I recommend reading this section of the usage guide:

https://copperhead.co/android/docs/usage_guide#built-in-user-facing-apps

DuckDuckGo isn't going to be *enforced* anywhere and we're going to be moving away from it in Chromium as the default once we decide on the best alternative.

**Comment by thestinger** [comment]
You aren't forced to use the default Search app. I'm not aware of an alternative implementing the relevant APIs for other apps, but you can still disable it. If there was a minimal, actively maintained implementation with a choice of search engine it would already be shipped in CopperheadOS instead of the dead AOSP app. If you're interested in making something suitable, we'll replace it.

**Comment by thestinger** [comment]
Filed https://github.com/copperhead/bugtracker/issues/861 but we're not going to get to this ourselves for a long time since there are much higher priorities like the OS itself and more important apps like our plans for a camera app and encrypted storage provider app.
